# spelling.yml is blocked per https://github.com/check-spelling/check-spelling/security/advisories/GHSA-g86g-chm8-7r2p
name: Spell checking
on:
  pull_request_target:
  push:
    branches: ["**"]
    tags-ignore: ["**"]

jobs:
  spelling:
    name: Check Spelling
    permissions:
      contents: read
      pull-requests: read
      actions: read
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
      internal_state_directory: ${{ steps.spelling.outputs.internal_state_directory }}
    runs-on: ubuntu-latest
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      # note: If you use only_check_changed_files, you do not want cancel-in-progress
      cancel-in-progress: true
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: checkout-merge
      if: "contains(github.event_name, 'pull_request')"
      uses: check-spelling/checkout-merge@v0.0.0
    - name: check-spelling
      if: env.MERGE_FAILED != '1'
      id: spelling
      uses: check-spelling/check-spelling@v0.0.20-alpha6
      with:
        suppress_push_for_open_pull_request: 1
        extra_dictionaries:
          cspell:filetypes/filetypes.txt
          cspell:html/html.txt
          cspell:css/css.txt
        post_comment: 0
    - name: store-comment
      if: (failure() || steps.spelling.outputs.followup) && steps.spelling.outputs.internal_state_directory
      uses: actions/upload-artifact@v2
      with:
        retention-days: 1
        name: "check-spelling-comment-${{ github.run_id }}"
        path: |
          ${{ steps.spelling.outputs.internal_state_directory }}

  comment:
    name: Report
    runs-on: ubuntu-latest
    needs: spelling
    permissions:
      contents: write
      pull-requests: write
    if: always() && (needs.spelling.result == 'failure' || needs.spelling.outputs.followup) && needs.spelling.outputs.internal_state_directory
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: set up
      run: |
        mkdir /tmp/data
    - name: retrieve-comment
      uses: actions/download-artifact@v2
      with:
        name: "check-spelling-comment-${{ github.run_id }}"
        path: /tmp/data
    - name: comment
      uses: check-spelling/check-spelling@v0.0.20-alpha6
      with:
        custom_task: comment
        extra_dictionaries:
          cspell:filetypes/filetypes.txt
          cspell:html/html.txt
          cspell:css/css.txt
        internal_state_directory: /tmp/data
